books/urls.py
import os

from django.conf.urls import include, url

from django.conf import settings
from books.app_settings import BOOKS_STATICS_VIA_DJANGO

from books import views


urlpatterns = [

    # Book list:
    url(r'^$', views.home,
     kwargs={}, name='home'),
    url(r'^latest/$', views.latest,
     {}, name='latest'),
    url(r'^by-title/$', views.by_title,
     {}, 'by_title'),
    url(r'^by-author/$', views.by_author,
     {}, 'by_author'),
    url(r'^by-author/(?P<author_id>\d+)/$', views.by_title,
     {}, 'books_by_author'),
    url(r'^tags/(?P<tag>.+)/$', views.by_tag,
     {}, 'by_tag'),
    url(r'^by-popularity/$', views.most_downloaded,
     {}, 'most_downloaded'),

    # Tag groups:
    url(r'^tags/groups.atom$', views.tags_listgroups,
     {}, 'tags_listgroups'),

    # Book list Atom:
    url(r'^catalog.atom$', views.root,
     {'qtype': u'feed'}, 'root_feed'),
    url(r'^latest.atom$', views.latest,
     {'qtype': u'feed'}, 'latest_feed'),
    url(r'^by-title.atom$', views.by_title,
     {'qtype': u'feed'}, 'by_title_feed'),
    url(r'^by-author.atom$', views.by_author,
     {'qtype': u'feed'}, 'by_author_feed'),
    url(r'^by-author/(?P<author_id>\d+).atom$', views.by_title,
     {'qtype': u'feed'}, 'by_title_author_feed'),
    url(r'^tags/(?P<tag>.+).atom$', views.by_tag,
     {'qtype': u'feed'}, 'by_tag_feed'),
    url(r'^by-popularity.atom$', views.most_downloaded,
     {'qtype': u'feed'}, 'most_downloaded_feed'),

    # Tag groups:
    url(r'^tags/groups/(?P<group_slug>[-\w]+)/$', views.tags,
     {}, 'tag_groups'),

    url(r'^tags/groups/(?P<group_slug>[-\w]+).atom$', views.tags,
     {'qtype': u'feed'}, 'tag_groups_feed'),

    # Tag list:
    url(r'^tags/$', views.tags, {}, 'tags'),
    url(r'^tags.atom$', views.tags,
     {'qtype': u'feed'}, 'tags_feed'),

    # Add, view, edit and remove books:
    url(r'^book/add$', views.BookAddView.as_view(), name='book_add'),
    url(r'^book/(?P<pk>\d+)/view$', views.BookDetailView.as_view(), name='book_detail'),
    url(r'^book/(?P<pk>\d+)/edit$', views.BookEditView.as_view(), name='book_edit'),
    url(r'^book/(?P<pk>\d+)/remove$', views.BookDeleteView.as_view(), name='book_remove'),
    url(r'^book/(?P<book_id>\d+)/download$', views.download_book, name='book_download'),

    # Comments
    # FIXME (r'^comments/', include('django.contrib.comments.urls')),

    # Add language:
    url(r'^add/dc_language|language/$', views.add_language),
]


if BOOKS_STATICS_VIA_DJANGO:
    from django.views.static import serve
    # Serve static media:
    # urlpatterns += patterns('',
    urlpatterns += [
       url(r'^static_media/(?P<path>.*)$', serve,
           {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),

       # Book covers:
       url(r'^covers/(?P<path>.*)$', serve,
           {'document_root': os.path.join(settings.MEDIA_ROOT, 'covers')}),
    ]

pathagar/urls.py
import os

from django.conf.urls import include, url
#from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

from django.conf import settings
from books.app_settings import BOOKS_STATICS_VIA_DJANGO

from django.contrib.auth import views as auth_views

urlpatterns = [

    url(r'', include('books.urls')),


    # Comments
    # FIXME (r'^comments/', include('django.contrib.comments.urls')),

    # Auth login and logout:
    url(r'^accounts/login/$', auth_views.login, name='login'),
    url(r'^accounts/logout/$', auth_views.logout, name='logout'),

    # Admin:
    url(r'^admin/', include(admin.site.urls)),
]


if BOOKS_STATICS_VIA_DJANGO:
    from django.views.static import serve
    # Serve static media:
    # urlpatterns += patterns('',
    urlpatterns += [
       url(r'^static_media/(?P<path>.*)$', serve,
           {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),

       # Book covers:
       url(r'^covers/(?P<path>.*)$', serve,
           {'document_root': os.path.join(settings.MEDIA_ROOT, 'covers')}),
    ]

books/models.py
# Copyright (C) 2010, One Laptop Per Child
# Copyright (C) 2010, Kushal Das
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

import os
import os.path

from django.db import models
from django.core.files import File
from django.core.exceptions import ValidationError
from django.conf import settings
from django.forms.forms import NON_FIELD_ERRORS

from hashlib import sha256

from taggit.managers import TaggableManager #NEW

from books.uuidfield import UUIDField
from books.langlist import langs
from books.epub import Epub

def sha256_sum(_file): # used to generate sha256 sum of book files
    s = sha256()
    for chunk in _file:
        s.update(chunk)
    return s.hexdigest()

class Language(models.Model):
    label = models.CharField('language name', max_length=50, blank=False, unique=True)
    code = models.CharField(max_length=4, blank=True)

    def __unicode__(self):
        return self.label

    def __str__(self):
        return self.label

    def save(self, *args, **kwargs):
        '''
        This method automatically tries to assign the right language code
        to the specified language. If a code cannot be found, it assigns
        'xx'
        '''
        code = 'xx'
        for lang in langs:
            if self.label.lower() == lang[1].lower():
                code = lang[0]
                break
        self.code = code
        super(Language, self).save(*args, **kwargs)


class TagGroup(models.Model):
    name = models.CharField(max_length=200, blank=False)
    slug = models.SlugField(max_length=200, blank=False)
    #tags = TagableManager()

    class Meta:
        verbose_name = "Tag group"
        verbose_name_plural = "Tag groups"

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name


class Status(models.Model):
    status = models.CharField(max_length=200, blank=False)

    class Meta:
        verbose_name_plural = "Status"

    def __unicode__(self):
        return self.status

    def __str__(self):
        return self.status


class Author(models.Model):
    a_author = models.CharField('atom:author', max_length=200, unique=True)

    def __unicode__(self):
        return self.a_author

    def __str__(self):
        return self.a_author


class Book(models.Model):
    """
    This model stores the book file, and all the metadata that is
    needed to publish it in a OPDS atom feed.

    It also stores other information, like tags and downloads, so the
    book can be listed in OPDS catalogs.

    """
    book_file = models.FileField(upload_to='books')
    file_sha256sum = models.CharField(max_length=64, unique=True)
    mimetype = models.CharField(max_length=200, null=True)
    time_added = models.DateTimeField(auto_now_add=True)
    tags = TaggableManager(blank=True)
    downloads = models.IntegerField(default=0)
    a_id = UUIDField('atom:id')
    a_status = models.ForeignKey(Status, blank=False, null=False, default=settings.DEFAULT_BOOK_STATUS)
    a_title = models.CharField('atom:title', max_length=200)
    a_author = models.ForeignKey(Author, blank=False, null=False)
    a_updated = models.DateTimeField('atom:updated', auto_now=True)
    a_summary = models.TextField('atom:summary', blank=True)
    a_category = models.CharField('atom:category', max_length=200, blank=True)
    a_rights = models.CharField('atom:rights', max_length=200, blank=True)
    dc_language = models.ForeignKey(Language, blank=True, null=True)
    dc_publisher = models.CharField('dc:publisher', max_length=200, blank=True)
    dc_issued = models.CharField('dc:issued', max_length=100, blank=True)
    dc_identifier = models.CharField('dc:identifier', max_length=50, \
    help_text='Use ISBN for this', blank=True)
    cover_img = models.FileField(blank=True, upload_to='covers')

    def validate_unique(self, *args, **kwargs):
        if not self.file_sha256sum:
            self.file_sha256sum = sha256_sum(self.book_file)
        unicity = self.__class__.objects.filter(file_sha256sum=self.file_sha256sum)
        if self.pk is not None:
            unicity = unicity.exclude(pk=self.pk)
        if unicity.exists():
            raise ValidationError({
                NON_FIELD_ERRORS:['The book already exists in the server.',]})

    def save(self, *args, **kwargs):
        assert self.file_sha256sum
        if not self.cover_img:
            # FIXME: we should use mimetype
            if self.book_file.name.endswith('.epub'):
                # get the cover path from the epub file
                epub_file = Epub(self.book_file)
                cover_path = epub_file.get_cover_image_path()
                if cover_path is not None and os.path.exists(cover_path):
                    cover_file = File(open(cover_path, "rb"))
                    self.cover_img.save(os.path.basename(cover_path), # pylint: disable=no-member
                                        cover_file)
                epub_file.close()

        super(Book, self).save(*args, **kwargs)

    class Meta:
        ordering = ('-time_added',)
        get_latest_by = "time_added"

    def __unicode__(self):
        return self.a_title

    def __str__(self):
        return self.a_title

    @models.permalink
    def get_absolute_url(self):
        return ('book_detail', [self.pk])

books/forms.py
# Copyright (C) 2010, One Laptop Per Child
# Copyright (C) 2010, Kushal Das
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

from django.forms import ModelForm
from books.models import Book, Language, Author

class BookForm(ModelForm):
    # dc_language = ModelChoiceField(Language.objects, widget=SelectWithPop)

    class Meta:
        model = Book
        exclude = ('mimetype', 'file_sha256sum', )

    def save(self, commit=True):
        """
        Store the MIME type of the uploaded book in the database.

        This is given by the browser in the POST request.

        """
        instance = super(BookForm, self).save(commit=False)
        book_file = self.cleaned_data['book_file']
        if instance.mimetype is None:
            instance.mimetype = book_file.content_type
        if commit:
            instance.save()
        return instance


class AuthorForm(ModelForm):
    class Meta:
        model = Author
        exclude = ()


class AddLanguageForm(ModelForm):
    class Meta:
        model = Language
        exclude = ('code',)

books/templates/books/book_confirm_delete.html
{% extends "base.html" %}

{% block title %}Are you shure?{% endblock %}

{% block script %}
$(document).ready(function()
{
  $(".hidden_body").hide();
  $(".hidden_head").click(function()
  {
    $(this).next(".hidden_body").slideToggle(100);
  });
  $('#id_dc_identifier').example('ISBN');
});
{% endblock %}

{% block head %}<script type="text/javascript" src="{{ STATIC_URL }}js/RelatedObjectLookups.js"></script>{% endblock %}

{% block content %}
<form  enctype="multipart/form-data" action="{% url 'book-remove' book.pk %}"
method="POST">{% csrf_token %}
<fieldset>
<legend>Are you shure you want to remove {{ book.a_title }}?</legend>
<div class="span-3">
<a href="{% url 'books.views.home' %}">Cancel</a>
<input type="submit" value="Remove">
</div>
</fieldset>
</form>
{% endblock %}

books/templates/books/book_detail.html
{% extends "base.html" %}
{% load tagging_tags %}
{% load comments %}

{% block title %}{{ book.a_title }} :: Pathagar Book Server{% endblock %}

{% block script %}
  {{ block.super }}
  $('#search').example('Book Search...');
{% endblock %}

{% block content %}

<div id="content">

<h1 class="alt">{{ book.a_title }}</h1>
<h2>by <span class="alt">{{ book.a_author }}</span></h2>
<hr class="space">
{% if user.is_authenticated %}
<div class="span-3">
<a class="button" href="{% url 'book-edit' book.pk %}">Edit</a>
<a class="button" href="{% url 'book-remove' book.pk %}">Remove</a>
</div>
<hr class="space">
<hr class="space">
<div class="span-2"><label>Status:</label></div>
<div class="span-3">{{ book.a_status }}</div>
<hr class="space">
{% endif %}

{% if book.tags.count != 0 %}
  <div class="span-2"><label>Tags:</label></div>
  <div class="span-10">
  {% for tag in book.tags.all %}
    <a class="button" href="{% url 'by_tag' tag.name %}">{{ tag.name }}</a>
  {% endfor %}
  </div>
  <hr class="space">
{% endif %}
<div class="span-16 colborder">
<div class="span-2"><label>Language:</label></div>
{% ifnotequal book.dc_language None %}
<div class="span-3">{{ book.dc_language }}</div>
{% else %}
<div class="span-3">Unknown</div>
{% endifnotequal %}
<hr class="space">
<div class="span-2"><label>Downloads:</label></div>
<div class="span-3">{{ book.downloads }}</div>
<hr class="space">
<div class="span-2"><label>Publisher:</label></div>
<div class="span-3">{{ book.dc_publisher }}</div>
<hr class="space">
<div class="span-2"><label>Published:</label></div>
<div class="span-3">{{ book.dc_issued }}</div>
<hr class="space">
<div class="span-2"><label>Rights:</label></div>
<div class="span-3">{{ book.dc_rights }}</div>
<hr class="space">
<div class="span-16">
<p>
{{ book.a_summary }}
</p>
</div>
<hr>
{% if allow_user_comments %}

<div class="span-16">
<label>Readers comments:</label>
</div>
<hr class="space">

{% get_comment_list for book as comment_list %}
{% for comment in comment_list %}
<div class="span-16"><b> {{ comment.user_name }} said: </b>{{ comment.comment }}</div>
<hr class="space">
{% endfor %}

<hr>

<div class="span-16">
<label>Add your comment:</label>
</div>

{% get_comment_form for book as form %}
<form action="{% comment_form_target %}" method="post">
{% csrf_token %}

{{ form.content_type }}
{{ form.object_pk }}
{{ form.timestamp }}
{{ form.security_hash }}
<input type="hidden" name="next" value="{% url 'book-detail' book_id=book.pk %}" />

<div class="span-4"><label for="id_your_name">Your name:</label></div>
{{ form.name }}
<hr class="space">

<div class="span-4"><label for="id_comment">Your comment:</label></div>
{{ form.comment }}
<hr class="space">

<input type="hidden" name="email" value="fake_emai@kfake.org" />
<input type="hidden" name="url" value="http://faksite.org" />

<input type="submit" name="submit" value="Post">
</form>


{% endif %}
</div>

<div class="span-6 last" id="sidebar">
{% if  book.cover_img %}
<img src="{{ book.cover_img.url }}" alt="Cover" width=150px/>
{% else %}
<img src="{{ STATIC_URL }}images/generic_cover.png" alt="Cover" width=150px/>
{% endif %}
<hr class="space">
<a class="download" href="{% url 'books.views.download_book' book.pk %}">Download book</a>
</div>


</div>

{%  endblock %}

books/templates/books/book_form.html
{% extends "base.html" %}

{% block title %}{% if action == 'add' %}
Add Book
{% else %}
Edit Book
{% endif %}
{% endblock %}

{% block script %}
$(document).ready(function()
{
  $(".hidden_body").hide();
  $(".hidden_head").click(function()
  {
    $(this).next(".hidden_body").slideToggle(100);
  });
  $('#id_dc_identifier').example('ISBN');
});
{% endblock %}

{% block head %}<script type="text/javascript" src="{{ STATIC_URL }}js/RelatedObjectLookups.js"></script>{% endblock %}

{% block content %}
<form  enctype="multipart/form-data"
{% if action == 'add' %}
  action="{% url 'book-create' %}"
{% else %}
  action="{% url 'book-edit' book.pk %}"
{% endif %}
method="POST">{% csrf_token %}
<fieldset>
<legend>
{% if action == 'add' %}
Add Book
{% else %}
Edit Book
{% endif %}
</legend>

{% if form.non_field_errors %}
    <div class="alert alert-error">
        <strong>{{ form.non_field_errors }}</strong>
    </div>
{% endif %}

<div class="span-3 required"><label for="id_book_file">File:</label></div>
<div class="span-4">{{ form.book_file }}</div>
{{ form.book_file.errors }}
<hr class="space">
<div class="span-3 required"><label for="id_a_title">Title:</label></div>
<div class="span-4">{{ form.a_title }}</div>
{{ form.a_title.errors }}
<hr class="space">
<div class="span-3 required"><label for="id_a_author">Author:</label></div>
<div class="span-4">{{ form.a_author }}</div>
{{ form.a_author.errors }}
<hr class="space">
<div class="span-3 required"><label for="id_a_status">Status:</label></div>
<div class="span-4">{{ form.a_status }}</div>
{{ form.a_status.errors }}
<hr class="space">
<div class="span-3"><label for="id_tags">Tags:</label></div>
<div class="span-4 last">{{ form.tags }}</div>
<hr class="space">
<div class="span-3"><label for="id_a_summary">Summary:</label></div>
<div class="span-4"></div><div class="span-8">{{ form.a_summary  }}</textarea></div>
<hr class="space">
<div class="span-3"><label for="id_dc_language">Language:</label></div>
<div class="span-4">
{{ form.dc_language }}
</div>
<hr class="space">

<div>
<p class="hidden_head">Optional information <a href="#">(click to expand)</a></p>
<div class="hidden_body">
<div class="span-3"><label for="id_a_category">Category:</label></div>
<div class="span-4">{{ form.a_category }}</div>
<hr class="space">
<div class="span-3"><label for="id_a_rights">Rights:</label></div>
<div class="span-4">{{  form.a_rights}}</div>
<hr class="space">
<div class="span-3"><label for="id_dc_publisher">Publisher:</label></div>
<div class="span-4">{{  form.dc_publisher }}</div>
<hr class="space">
<div class="span-3"><label for="id_dc_issued">Issued: </label></div>
<div class="span-4">{{  form.dc_issued }}</div>
<hr class="space">
<div class="span-3"><label for="id_dc_identifier">Identifier: </label></div>
<div class="span-4">{{  form.dc_identifier }}</div>
<hr class="space">
<div class="span-3"><label for="id_downloads">Downloads:</label></div>
<div class="span-4 last">{{ form.downloads }}</div>
<hr class="space">
<div class="span-3"><label for="id_dc_identifier">Cover image: </label></div>
<div class="span-4">{{  form.cover_img }}</div>
<hr class="space">
</div>
</div>

<div class="span-4 prepend-21 last">
<input type="submit"
{% if action = 'add' %}
  value="Add">
{% else %}
  value="Edit">
{% endif %}
</div>
</fieldset>
</form>
{% endblock %}

books/templates/books/book_list.html
{% extends "base.html" %}
{% load tagging_tags %}

{% block title %}Welcome to the Pathagar book server{% endblock %}

{% block script %}
  {{ block.super }}
  {% if q != None %}
  $('#search').val('{{ q }}');
  {% else %}
  $('#search').example('Book Search...');
  {% endif %}
{% endblock %}

{% block feed_link %}
<a class="feed-link"
{% if list_by == 'latest' %}
    href="{% url 'latest_feed' %}{{ qstring }}"
{% endif %}
{% if list_by == 'by-title' %}
    href="{% url 'by_title_feed' %}{{ qstring }}"
{% endif %}
{% if list_by == 'by-author' %}
    href="{% url 'by_author_feed' %}{{ qstring }}"
{% endif %}
{% if list_by == 'by-tag' %}
    {% if tag %}
        href="{% url 'by_tag_feed' tag.name %}{{ qstring }}"
    {% else %}
        href="#"
    {% endif %}
{% endif %}
{% if list_by == 'most-downloaded' %}
    href="{% url 'most_downloaded_feed' %}{{ qstring }}"
{% endif %}
><img src="{{ STATIC_URL }}images/feed.png" alt="Feed Icon" />Subscribe to Feed</a>
{% endblock %}

{% block content %}

<div class="span-17 colborder" id="content">
{% for book in book_list %}
  <div class="span-3 cover">
  {% if book.cover_img %}
    <img src="{{ book.cover_img.url }}" alt="Cover" width=100px/>
  {% else %}
    <img src="{{ STATIC_URL }}images/generic_cover.png" alt="Cover" width=100px/>
  {% endif %}
  </div>
  <div class="prepend-3">
  <h1 class="bookname">
    <a href="{% url 'book-detail' book_id=book.pk %}">{{ book.a_title }}</a>
  </h1>
  <h2>by <span class="alt">{{ book.a_author }}</span></h2>
  {% tags_for_object book as tag_list %}
  {% if book.tags.count != 0 %}
    <div class="span-10"> 
    {% for tag in book.tags.all %}
      <a class="button" href="{% url 'by_tag' tag.name %}">{{ tag.name }}</a>
    {% endfor %}
    </div>
  {% endif %}
  <div class="span-10"> 
  <p>{{ book.a_summary }}</p>
  </div>
  </div>
  <div class="span-3 prepend-14 last"><em><a class="download" href="{% url 'books.views.download_book' book.pk %}">Download</a></em></div>
  <hr/>
{%  endfor %}

<div class="prepend-12 pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}{% if q %}&q={{ q }} {% endif %}"><img src="{{ STATIC_URL }}images/go-previous.png" alt="previous"></a>
        {% endif %}

        <span class="current-page">
            &nbsp;{{ page_obj.number }} of {{ paginator.num_pages }}&nbsp;
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}{% if q %}&q={{ q }} {% endif %}"><img src="{{ STATIC_URL }}images/go-next.png" alt="next"></a>
        {% endif %}
    </span>
</div>
</div>

<div class="span-6 last" id="sidebar">
  <hr class="space">
  <div class="linkbox">
  <h3 class="caps">Statistics</h3>
  <div class="box">
  <ul>
      <li>Published ebooks in this server: <em>{{ published_books }}</em></li>
{% if user.is_authenticated %}
      <li>Unpublished ebooks in this server: <em>{{ unpublished_books }}</em></li>
{% endif %}
  </ul>
  <hr>
  {% if tag %}
    <ul>
      <li>Showing books with tag <em>{{ tag.name }}</em></li>  
    </ul>
    <hr>
  {% endif %}
  {% ifnotequal paginator.count total_books %}
    <ul>
      <li>Number of ebooks in search result: <em>{{ paginator.count }}</em></li>
      <li>Showing matches <em>{{ page_obj.start_index }}</em> to <em>{{ page_obj.end_index }}</em></li>
  {% else %}
    <ul>
      <li>Showing entire collection.</li>
  {% endifnotequal %}
  </ul>
  </div>
  </div>
</div>

{%  endblock %}

books/templates/books/tag_list.html
{% extends "base.html" %}

{% block title %}{{ book.a_title }} :: Pathagar Book Server{% endblock %}

{% block script %}
  {{ block.super }}
  $('#search').example('Book Search...');
{% endblock %}

{% block content %}

<div id="content">

<h1 class="alt">Tags {% if tag_group %} by {{ tag_group }}{% endif %}</h1>
<hr class="space">

{% if tag_list %}
<div class="span-2"><label>Tags:</label></div>
<div class="span-10">
{% for tag in tag_list %}
<a class="button" href="{% url 'by_tag' tag.name %}">{{ tag.name }}</a>
{% endfor %}
</div>
<hr class="space">
{% endif %}

{% if tag_group_list %}
<div class="span-2"><label>Tag groups:</label></div>
<div class="span-10">
{% for tag_group in tag_group_list %}
<a class="button" href="{% url 'tag_groups' tag_group.slug %}">{{ tag_group.name }}</a>
{% endfor %}
</div>
<hr class="space">
{% endif %}

{%  endblock %}